#+options: toc:nil num:nil author:nil creator:nil date:nil

guix-packaging (aka "guix-packaging.el") provides tools to create and maintain
Guix packages quickly and with confidence.

*** Commands

**** ~M-x~ ~guix-packaging-insert-input~
Prompts for a package string with completion, for example ~ruby@2.7.2~, and
inserts the corresponding Guix input form such as ~("ruby@2.7.2" ,ruby-2.7)~. It
reads the Guile source code to find the appropriate symbol name, so it might not
work with some packages that have unusual source code.

**** ~M-x~ ~guix-packaging-hash-git~
Saves the Guix hash to the kill ring for a git repository URL (the one at point
by default) at a given tag.

**** ~M-x~ ~guix-packaging-go-mod-to-checklist-dwim~
Turns go module definitions into an org/markdown checklist, suitable to keep
track of packaging progress.

**** ~M-x~ ~guix-packaging-go-mod-to-checkbox~
Replace a single go module definition with a checkbox.

*** Snippets

**** scheme mode
The ~guix-go~ snippet creates the skeleton of a go module package and assists
you in quickly filling it out. You first provide the import path, from which the
snippet infers the symbol & package names, the repo URL, the hash, and the
homepage. All of these are presented in the snippet as default values that you
can change as you go for unusual cases.

The ~guix-go-noversion~ snippet is similar but instead provides a package
skeleton suitable for those modules which don't have any releases.

**** sgml, web, markdown, and org modes
The ~guix-badge~ snippet inserts the HTML for a Repology badge showing the
package status in Guix and linking to the project page in Repology, handy for
project status pages.

*** Vision

Writing and maintaining Guix packages in Emacs should be a breeze. The
information you need should be ready at your fingertips and any chores or
guesswork that can be reasonably automated should be. In particular, maintainers
of Emacs packages in Guix should be able to complete the entire cycle of package
creation, testing, installation, updates, maintenence and discovery within
Emacs.
